### ISSUE TITLE
interactive() function returns false

### ISSUE THREAD

**Issue by amnonma** [VisualText/nlp-engine#388]
interactive() function should return true inside VSCode NLP++ environment.
Should return false when we are in a runtime environment (whether interpreted or compiled).
Should be a trivial fix.
Worked around it, so low priority now. @ddehilster

**Comment by dehilsterlexis** [comment]
@amnonma the only distinction that could be made is whether it was called as an intercepted executable with arguments or through the c++ libraru. Does that do what you want?

**Comment by dehilsterlexis** [comment]
@amnonma turns out that setFinteractive is never called. I will change that.
