### ISSUE TITLE
Dicttokz pass omits adding newline (NL attr) and whitespace attrs

### ISSUE THREAD

**Issue by amnonma** [VisualText/nlp-engine#398]
HIGHEST PRIORITY.
The dicttokz pass must count newlines (including blank lines).
Needs to put the count in NL attribute on subsequent non-whitespace node.
Useful also would be SOL and EOL (start/end of line) attributes.
Useful also is count of TAB and SPACE chars at start of line (indentation).
(Actually useful on each node of parse tree!)
You may not have latest version of this, in NLP-ENGINE.
Handle Linux vs Windows newline styles.
I should probably take this on.
@ddehilster

**Comment by dehilsterlexis** [comment]
@amnonma let's talk about this. There is a lot to take in here.
