### ISSUE TITLE
DICT Phrases: Some don't work.

### ISSUE THREAD

**Issue by amnonma** [VisualText/nlp-engine#407]
You could require punctuation to have a backslash, as one format option.

Examples:

14 - 62 ( G ) s=vCODE class="mfr-dlr" type="misc" usecode=C11010

1 - Phrase is made without the parentheses and "G".
2 - Suggested node should be _vCODE, not a generic "_phrase" node.

I 49 - 1628 ( 4 ) ( C ) s=vCODE class="mfr-dlr" type="misc" state=NC usecode=C11010

3 - This phrase doesn't seem to work at all.

@ddehilster

**Comment by dehilsterlexis** [comment]
@amnonma never thought of doing such complex dictionary phrases in the beginning so I never tested these types of phrases. I will look into requiring a backslash for equal signs given that is the key in parsing the phrase.

**Comment by dehilsterlexis** [comment]
@amnonma the dictionary is assumed to work only with lower case. If I change the uppercase letter in the dict file to lowercase, it works for me.
