### ISSUE TITLE
Backquote char not recognized as punctuation

### ISSUE THREAD

**Issue by amnonma** [VisualText/nlp-engine#415]
The backquote character here:     ` 
was not treated as punctuation.
With or without a backslash in front, it gives a syntax error in an NLP++ rule.
@dehilsterlexis

**Comment by dehilsterlexis** [comment]
I just tested it and it worked for me.
```
    _LINE [427,432,427,432,4,24,node]
      ` [427,427,427,427,0,0,punct, ("SP" 1) ("NL" 1)]
      this [428,431,428,431,0,0,alpha, ("NOSP" 1) ("lower" 1)]
      ` [432,432,432,432,0,0,punct, ("NOSP" 1)]
 ```

**Comment by dehilsterlexis** [comment]
@amnonma there is a strhaspunct function I made recently. That could work.
