### ISSUE TITLE
Dictionary Case Error 

### ISSUE THREAD

**Issue by ashtonomy** [VisualText/nlp-engine#462]
Dictionary isn't matching uppercased words when dictionary keys are uppercase. Minimum example:

![image](https://github.com/VisualText/nlp-engine/assets/100785983/e82e2bfd-46e4-464d-bbbf-15f281c3a273)

Text is on the left, final tree is in the middle, and dictionary is on the right. Compare this to :

![image](https://github.com/VisualText/nlp-engine/assets/100785983/93db1f1d-e685-498c-b8aa-39647fef1ce3)

**Comment by dehilsterlexis** [comment]
@ashtonomy definitely a bug!

**Comment by dehilsterlexis** [comment]
@ashtonomy I am making it now so that the dictionary will try to first match case sensitive, then case insensitive.
