### ISSUE TITLE
Pesky multi-word dictionary matching issue

### ISSUE THREAD

**Issue by ashtonomy** [VisualText/nlp-engine#463]
I'm encountering an issue with certain multi-word dictionary keys that results in only partial matches when the full key is present. It only occurs in certain situations and I haven't been able to find a consistent cause. See example below, in which you would expect all matches to be reduced to _phrase, with a "var" attribute:

![image](https://github.com/VisualText/nlp-engine/assets/100785983/d4e5ee08-7154-4306-bcab-621d91ad763f)

**Comment by dehilsterlexis** [comment]
Fixed
