### ISSUE TITLE
Knowledge base concept pointers

### ISSUE THREAD

**Issue by amnonma** [VisualText/nlp-engine#487]
I believe the NLP-ENGINE for NLP++ does not support saving knowledge base pointers of type CONCEPT.
Nor is there a way to point from a KB concept to another concept, in the .KBB files.
Correct me if I am wrong.
(KB pointers to concepts enable the Conceptual Grammar KB to represent arbitrary GRAPHS, beyond the hierarchical backbone.)
@ddehilster 
@dehilsterlexis

**Comment by ddehilster** [comment]
Not true. The KBB does  allow for saving concepts pointing to other concepts.
